[global]
out-dir = "target"
profile = "debug"
sha1.shell = "git rev-parse HEAD"
version.shell = "toml get werk-cli/Cargo.toml package.version"
version.info = "Version from Cargo.toml: {}"

[command.build]
build = ["example{EXE_SUFFIX}"]
post-message = "Build done for profile '{profile}' (SHA1 {sha1}, version {version})"
command = "sleep 1"

[command.clear]
command = "rm -rf target/yikes.o target/src/test.o target/example"

[build.'{profile}/werk']
command = "cargo build -p werk-cli --profile={profile}"

[build.'%.o']
in = "{%}.c"
depfile = "{%}.c.d"
command = [
    "sleep 1",
    "clang -c -o <out> <in>",
    { string = "sleep 1", info = "would sleep while compiling <in>" },
]

[build.'%.c.d']
in = "{%}.c"
command = "clang -MM -MT <out> -MF <out> <in>"

[build.'example{EXE_SUFFIX}']
in = [{ glob = "src/**/*.c", then = "{*:.c=.o}" }, "yikes.o"]
command = ["clang -o <out> <in*>", "sleep 1"]

[build.'%.(frag|vert|comp).spv']
in = "{%}.{0}"
depfile = "{%}.{0}.d"
command = "glslc -o <out> <in>"

[build.'%.(frag|vert|comp).d']
in = "{%}.{0}"
command = "glslc -MM -MT <out> -MF <out> <in>"

[build.'%.spv']
in = "{%}.slang"
depfile = "{%}.slang.d"
command = "slangc -o <out> <in>"

[build.'%.slang.d']
in = "{%}.slang"
command = "slangc -MM -MT <out> -MF <out> <in>"
