[config]
out-dir = "../../target/examples/c"

[global]
cc.which = "clang"
ld = "{cc}"
profile = "debug"
executable = "{profile}/example{EXE_SUFFIX}"

[global.cflags]
from = "profile"
match.'debug' = ["-g", "-O0", "-fcolor-diagnostics"]
match.'release' = ["-O3", "-fcolor-diagnostics"]
match.'%' = { error = "Unknown profile; valid options are 'debug' and 'release'" }

# Build an object file from a C source file.
[build.'{profile}/%.o']
in = "{%}.c"
depfile = "/{profile}/{%}.c.d"
command = "{cc} -c {cflags*} -o <out> <in>"

# Build the depfile for an object file.
[build.'{profile}/%.c.d']
in = "{%}.c"
# Note: For werk to understand the depfile, it must be in the format of a
# Makefile, and the paths mentioned inside must be absolute and native OS paths.
# Werk automatically interprets its contents and re-translates it back into
# workspace-relative or out-dir-relative abstract paths.
command = "{cc} -MM -MT <in*> -MF <out> <in>"

# Build the executable.
[build.'{executable}']
# in = { glob = "*.c", then = "/{profile}{:.c=.o}" }
in = { glob = "*.c", match.'%.c' = "/{profile}{%}.o" }
command = "{ld} -o <out> <in*>"

# Build the executable.
[command.build]
build = ["{executable}"]
post-message = "Build done for profile '{profile}'"

# Build and run the executable.
[command.run]
build = "build"
command = "<executable>"
# Echo the output of the command to the terminal unconditionally.
capture = false
