[package]
name = "werk-parser"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
indexmap.workspace = true
toml_edit = "0.22.22"
thiserror.workspace = true
unicode-ident = "1.0.13"
winnow.workspace = true
regex.workspace = true
