[package]
name = "werk-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "werk"
path = "main.rs"

[dependencies]
ahash.workspace = true
anstream = "0.6.18"
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
clio = "0.3.5"
crossterm = "0.28.1"
flume = "0.11.1"
indexmap.workspace = true
owo-colors = "4.1.0"
parking_lot.workspace = true
ratatui = "0.29.0"
tokio.workspace = true
tracing-subscriber = "0.3.18"
tracing.workspace = true
werk-fs.workspace = true
werk-parser.workspace = true
werk-runner.workspace = true
anstyle-query = "1.1.2"
anstyle-wincon = "3.0.6"
